name: Build and Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Test authentication with GitHub Packages
        run: |
          curl -v -u ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} https://maven.pkg.github.com/DeepakJ99/api-spec/
      - name: Set up Maven settings
        run: |
          mkdir -p ~/.m2
          echo "<settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.GITHUB_TOKEN }}</password>
              </server>
            </servers>
          </settings>" > ~/.m2/settings.xml
      - name: Build with Maven
        run: |
          mvn clean package -DskipTests

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: water-thingy-14072025
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker for GCP
        run: |
          gcloud auth configure-docker

      - name: Build Docker Image
        run: |
          docker build -t gcr.io/water-thingy-14072025/restaurant-svc:${{ github.sha }} .

      - name: Push Docker Image
        run: |
          docker push gcr.io/water-thingy-14072025/restaurant-svc:${{ github.sha }}